version: '3'

services:
  errbit:
    image: opendba/errbit:latest
    build: .
    ports:
      8083:8080
    links:
      - mongo
    networks:
      - errbitnet
      - frontend
    environment:
      - PORT=8080
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
      - VIRTUAL_HOST=ex.opendba.lv
      - VIRTUAL_PORT=8080
      - ERRBIT_HOST=ex.opendba.lv
  mongo:
    image: mongo:3.4
    volumes:
        - mongo_db:/data/db
    networks:
      - errbitnet

volumes:
    mongo_db:
        driver: local-persist
        driver_opts:
            mountpoint: /opt/docker-volumes/errbit/data

networks:
  errbitnet:
    driver: bridge
  frontend:
    external:
      name: local_frontend
